### ISSUE TITLE
USER STORY: Enhance the design of each page of the project

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#13]
As a **user**, I can **engage the content on each page of the website**, so that **I can understand the content on each page with it being easy on the eye**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That I am a user and on a certain page
**When** I am on that page looking at the content
**Then**  That it is easily readable and engaging

## Tasks

- [x] task 1 - Enhance the design of allauth pages
    
- [x] task 2 - Enhance the design of the home page
      
- [x] task 3 - Enhance the design of the pictures/products/gallery pages

- [x] task 4 - Enhance the design of the bag page

- [x] task 5 - Enhance the design of the checkout pages

- [x] task 6 - Enhance the design of the profile page
