### ISSUE TITLE
USER STORY: Create nav-bar with relevant content for navigation

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#15]
As a **user**, I can **access and see the necessary content on the nav-bar**, so that **it is easily reachable and have control on every page**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That I am a user on the website
**When** I want to see my account information
**Then**  I can access it on the nav-bar on every page
- Acceptance Criteria 2
**Given** That I am a user on the website
**When** I want to see if I am logged in or not
**Then** I can see it on the nav-bar
- Acceptance Criteria 3
**Given** That I am a user on the website
**When** I am on any page 
**Then** I can access all the necessary content for a e-commerce website 

## Tasks

- [x] task 1 - Create an account option with the necessary content
    
- [x] task 2 - Display the username as logged in and "you are not logged in" if not
      
- [x] task 3 - Display content required for filtering or links to all products

- [x] task 4 - Display Facebook link for Facebook page

- [x] task 5 - Display shopping cart to link to added products to shopping cart and add features to it (eg amount)
