### ISSUE TITLE
USER STORY: home page content

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#16]
As a **user**, I would like to **see an engaging landing page, with an attractive hero image and a bigger picture of what the website has to offer**, so that **I can make more informative decisions in an engaging way**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That I am on the landing page
**When** I enter the site
**Then** An enterprising and engaging image is displayed
- Acceptance Criteria 2
**Given** That I am on the landing page
**When** I enter the site
**Then** I know immediately what I can do as it is displayed simply and descriptively
- Acceptance Criteria 3
**Given** that I am on the landing page
**When** I look into the landing page
**Then**  I know where I can go and what I can do

## Tasks

- [x] task 1 - Add Hero image and a shop now button for immediate action
    
- [x] task 2 - Add niche product sections (divs) to give some insight into that particular product
      
- [x] task 3 - Add necessary Information regarding the site that is display immediately(free delivery, sales, etc.)
