### ISSUE TITLE
USER STORY: View Product Details

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#18]
As a **user**, I can **view the full details for a product**, so that **I can make an informed purchase decision**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That I am a user on the site
**When** I navigate to a product listing
**Then** the full details of the product are available
- Acceptance Criteria 2
**Given** That I am a user on the all products page
**When**  click on a product summary card
**Then**  I am taken to a page with the full details on the product

## Tasks

- [x] task 1 - Develop a product full details page template
    
- [x] task 2 - Develop product card template
      
- [x] task 3 - Link product card with product detail page
