### ISSUE TITLE
USER STORY: Add to Cart

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#22]
As a **user**, I can **add products that I want to buy to my shopping cart**, so that **I can proceed to purchase them**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That I am an unregistered user
**When** I find a product I want to purchase
And, I click on add to cart
**Then** the product is added to my shopping cart, ready for me to purchase
- Acceptance Criteria 2
**Given** that I am a User,
**When** I click add to cart on a product I have previously added to my cart
**Then** The quantity of that product in my cart increases by the amount I just added

## Tasks

- [x] task 1 - Develop a shopping cart functionality to track products users want to purchase.
    
- [x] task 2 - Enable the cart to be utilized when a user is logged in or not
      
- [x] task 3 - Develop check on add to cart functionality for product already existing in cart – if product exists, increase quantity appropriately
