### ISSUE TITLE
USER STORY: Fill out address details for checkout

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#28]
As a **user**, I can **provide my details**, so that **I can complete my order**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a User,
**When** I proceed to checkout
**Then** I am asked to enter my delivery and billing address
- Acceptance Criteria 2
**Given** that I am a user,
**When** I enter my billing address
**Then** I can use the same address for delivery without having to fill it out twice
- Acceptance Criteria 3
**Given** that I am a logged in user,
**When** I enter my address details,
**Then**  have the option to save the details I entered to my account
- Acceptance Criteria 4
**Given** that I am a logged in user,
**When**I get to the enter billing and delivery address screen
**Then**  I have the option to use previously saved address(es) details
- Acceptance Criteria 5
**Given** hat I am a registered user, not logged in
**When** I progress to enter the address information – I have the ability to login
**Then**  return to the same screen and use previously saved address details.

## Tasks

- [x] task 1 - Develop checkout page to collect billing and delivery address details
    
- [x] task 2 - Enable option to use billing address for delivery address
      
- [x] task 3 -  Enable option for users to save address details to their account

- [x] task 4 -  Enable logged in users to select previously saved addresses instead of manual completion of the form
