### ISSUE TITLE
USER STORY: Django Setup

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#3]
As a **Developer**, I can **set up Django and install the supporting libraries needed**, so that **I am ready to start development**

## Tasks

- [x] task 1 - Install Django
    
- [x] task 2 - Install dj_database_url psycopg2
      
- [x] task 3 - Create a requirements.txt file

- [x] task 4 - Install django-crispy-forms

- [x] task 5 - Install Pillow

- [x] task 6 - Install Django-allauth

- [x] task 7 - Create new instance in Postgres SQL and connect database to code

- [x] task 8 - Install Gunicorn

- [x] task 9 - Create the Django project

- [x] task 10 - Create the first app
