### ISSUE TITLE
USER STORY: Edit Account

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#32]
As a **user**, I can **edit the details/address stored on my account**, so that **If I move, I can change my details**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I have a user profile,
And, I am logged into my profile
**When** I navigate to my profile
**Then** I have the ability to edit my address on my account
- Acceptance Criteria 2
**Given** that I have a user profile,
And, I am logged into my profile
**When** I navigate to my profile
**Then** I have the option to delete the address’s

## Tasks

- [x] task 1 - Develop the ability for users to save addresses to their profile
    
- [x] task 2 - Develop the ability for users to edit the addresses on their profile
      
- [x] task 3 - Develop the ability for users to delete the addresses on their profile
