### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#38]
As a **Store Owner**, I would **like employees to be able to edit product details on the site easily**, so that **any corrections needed can be carried out when required**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That I am an employee
**When** I log into the site
**Then** I should have the option to edit a product
- Acceptance Criteria 2
**Given** That I am a logged in employee
**When** I select which product to edit
**Then** I am directed to a form from which I can edit the existing product data
- Acceptance Criteria 3
**Given** That I am a logged in employee
**When** I edit product details within the form and submit the changes
**Then** the changes I made appear on the site

## Tasks

- [x] task 1 - Develop the option for employees to edit products
    
- [x] task 2 - Develop validation for the form to ensure product information is complete
      
- [x] task 3 - Develop a form for employees to edit the product data
