### ISSUE TITLE
USER STORY: Favorites 

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#40]
As a **user**, I can **choose my favorites from the products**, so that **I can buy them later**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** That i am a user
**When** I see the list of products
**Then** I can choose which one i want to put as favorites
- Acceptance Criteria 2
**Given** That i am a user
**When** I want to see my list of products
**Then** I can go to a page to see my favorites
- Acceptance Criteria 3
**Given** That i am a user
**When** I want to remove a product from my favorites
**Then** There is a button letting me do so

## Tasks

- [x] task 1 - Implement a favorites page
    
- [x] task 2 - Make each product with add to favorites/added to favorites
      
- [x] task 3 - Develop function to delete product
