### ISSUE TITLE
USER STORY: Headline Update

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#42]
As a **site owner**, I can **edit the text content on the landing page**, so that **I can let user know new information**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that i am a site owner
**When** There is a notification/news i want users to know
**Then** It is displayed on the home page
- Acceptance Criteria 2
**Given** that i am a site owner
**When** I want to edit the text content
**Then** I can go to a page and edit it

## Tasks

- [x] task 1 - Implement a form to edit the content
    
- [x] task 2 - Add a section in the landing page to edit content
      
- [x] task 3 - Restrict the size of the content
