### ISSUE TITLE
USER STORY: Deployment to Heroku

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#5]
As a **Developer**, I want to **deploy the app to Heroku**, so that **I can confirm everything works before development of the site.**

## Tasks

- [x] task 1 - Update code for deployment
    
- [x] task 2 - Create new Heroku app
      
- [x] task 3 - Connect Heroku to the PostgreSQL database

- [x] task 4 - Implement and add Secret Key to project and Heroku config var
