### ISSUE TITLE
USER STORY: Create a User Account

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/Yugen#6]
As a **user**, I would like **to be able to create an account**, so that **I don’t have to enter my details every time I place an order**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am an unregistered user
And, I am on the user registration page
**When** I enter my username, email address and password
And, I click on the register button
**Then** the system creates me an account
- Acceptance Criteria 2
**Given** that I have an account
And, I have items in my cart
**When**I navigate to checkout
**Then** I have my address information ready to be used

## Tasks

- [x] task 1 - Develop ability for users to register for a user account
    
- [x] task 2 - Develop a  page and button in the nav bar to direct users to the registration page
      
- [x] task 3 - Remove the register button from the nav bar when users are logged in

- [x] task 4 - Create a User Registration form
